#!/bin/bash

function install_oasgen {

  echo "oasgen=1" >> $HOME/.oasgenrc
  git clone https://github.com/udistrital/oasgen.git $HOME/.oasgen
  echo "export OASGEN_PATH=\$HOME/.oasgen/bin" >> $HOME/.bashrc
  echo "PATH=\$PATH:\$HOME/.oasgen/bin" >> $HOME/.bashrc
}

install_oasgen
